export const STICKER_CATEGORIES = [
  { id: 'headwear', labelKey: 'stickerCategoryHeadwear' },
  { id: 'emojis', labelKey: 'stickerCategoryEmojis' },
  { id: 'police', labelKey: 'stickerCategoryPolice' },
  { id: 'props', labelKey: 'stickerCategoryProps' },
]

export const MUGSHOT_STICKERS = [
  {
    id: 'banditMask',
    labelKey: 'stickerBanditMask',
    category: 'headwear',
    default: { x: 0, y: -55, scale: 1, rotation: 0 },
  },
  {
    id: 'policeHat',
    labelKey: 'stickerPoliceHat',
    category: 'headwear',
    default: { x: 0, y: -110, scale: 1, rotation: 0 },
  },
  {
    id: 'sheriffHat',
    labelKey: 'stickerSheriffHat',
    category: 'headwear',
    default: { x: 0, y: -115, scale: 1.1, rotation: 0 },
  },
  {
    id: 'militaryBeret',
    labelKey: 'stickerMilitaryBeret',
    category: 'headwear',
    default: { x: 0, y: -100, scale: 0.9, rotation: 0 },
  },
  {
    id: 'firefighterHelmet',
    labelKey: 'stickerFirefighterHelmet',
    category: 'headwear',
    default: { x: 0, y: -115, scale: 1, rotation: 0 },
  },
  {
    id: 'hardHat',
    labelKey: 'stickerHardHat',
    category: 'headwear',
    default: { x: 0, y: -115, scale: 1, rotation: 0 },
  },
  {
    id: 'chefHat',
    labelKey: 'stickerChefHat',
    category: 'headwear',
    default: { x: 0, y: -125, scale: 1, rotation: 0 },
  },
  {
    id: 'pirateHat',
    labelKey: 'stickerPirateHat',
    category: 'headwear',
    default: { x: 0, y: -110, scale: 1.1, rotation: 0 },
  },
  {
    id: 'captainHat',
    labelKey: 'stickerCaptainHat',
    category: 'headwear',
    default: { x: 0, y: -110, scale: 1, rotation: 0 },
  },
  {
    id: 'vikingHelmet',
    labelKey: 'stickerVikingHelmet',
    category: 'headwear',
    default: { x: 0, y: -115, scale: 1.1, rotation: 0 },
  },
  {
    id: 'detectiveHat',
    labelKey: 'stickerDetectiveHat',
    category: 'headwear',
    default: { x: 0, y: -105, scale: 1, rotation: 0 },
  },
  {
    id: 'guiltyStampRect',
    labelKey: 'stickerGuiltyStampRect',
    category: 'police',
    default: { x: -100, y: -140, scale: 0.9, rotation: 0 },
  },
  {
    id: 'guiltyStampRound',
    labelKey: 'stickerGuiltyStampRound',
    category: 'police',
    default: { x: 100, y: 120, scale: 0.8, rotation: 0 },
  },
  {
    id: 'wantedRect',
    labelKey: 'stickerWantedRect',
    category: 'police',
    default: { x: 0, y: 140, scale: 0.9, rotation: 0 },
  },
  {
    id: 'handcuffs',
    labelKey: 'stickerHandcuffs',
    category: 'police',
    default: { x: 100, y: 60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'siren',
    labelKey: 'stickerSiren',
    category: 'police',
    default: { x: 0, y: -160, scale: 0.8, rotation: 0 },
  },
  {
    id: 'evidenceBag',
    labelKey: 'stickerEvidenceBag',
    category: 'police',
    default: { x: -110, y: 40, scale: 0.8, rotation: 0 },
  },
  {
    id: 'policeLineTape',
    labelKey: 'stickerPoliceLineTape',
    category: 'police',
    default: { x: 0, y: 0, scale: 0.9, rotation: 0 },
  },
  {
    id: 'caseClosedBoard',
    labelKey: 'stickerCaseClosedBoard',
    category: 'police',
    default: { x: 100, y: -30, scale: 0.8, rotation: 0 },
  },
  {
    id: 'innocentNote',
    labelKey: 'stickerInnocentNote',
    category: 'police',
    default: { x: -100, y: -30, scale: 0.8, rotation: 0 },
  },
  {
    id: 'goodBoyBadge',
    labelKey: 'stickerGoodBoyBadge',
    category: 'props',
    default: { x: -100, y: -100, scale: 0.9, rotation: 0 },
  },
  {
    id: 'pawMedal',
    labelKey: 'stickerPawMedal',
    category: 'props',
    default: { x: 100, y: -100, scale: 0.9, rotation: 0 },
  },
  {
    id: 'mamasHeart',
    labelKey: 'stickerMamasHeart',
    category: 'props',
    default: { x: 0, y: 100, scale: 0.9, rotation: 0 },
  },
  {
    id: 'pawPrints',
    labelKey: 'stickerPawPrints',
    category: 'props',
    default: { x: 0, y: 60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'pawNote',
    labelKey: 'stickerPawNote',
    category: 'props',
    default: { x: 0, y: -100, scale: 0.8, rotation: 0 },
  },
  {
    id: 'tennisBall',
    labelKey: 'stickerTennisBall',
    category: 'props',
    default: { x: -110, y: 100, scale: 0.7, rotation: 0 },
  },
  {
    id: 'bone',
    labelKey: 'stickerBone',
    category: 'props',
    default: { x: 110, y: 100, scale: 0.8, rotation: 0 },
  },
  {
    id: 'poop',
    labelKey: 'stickerPoop',
    category: 'props',
    default: { x: 0, y: -30, scale: 0.7, rotation: 0 },
  },
  {
    id: 'trashCan',
    labelKey: 'stickerTrashCan',
    category: 'props',
    default: { x: -90, y: -60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'megaphone',
    labelKey: 'stickerMegaphone',
    category: 'props',
    default: { x: 90, y: -60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'underArrest',
    labelKey: 'stickerUnderArrest',
    category: 'police',
    default: { x: -100, y: 140, scale: 0.8, rotation: 0 },
  },
  {
    id: 'tinyTerror',
    labelKey: 'stickerTinyTerror',
    category: 'police',
    default: { x: 110, y: -140, scale: 0.8, rotation: 0 },
  },
  {
    id: 'sparkles',
    labelKey: 'stickerSparkles',
    category: 'emojis',
    default: { x: -110, y: -100, scale: 0.8, rotation: 0 },
  },
  {
    id: 'napChampion',
    labelKey: 'stickerNapChampion',
    category: 'props',
    default: { x: -100, y: 60, scale: 0.9, rotation: 0 },
  },
  {
    id: 'bestSniffer',
    labelKey: 'stickerBestSniffer',
    category: 'props',
    default: { x: 100, y: 30, scale: 0.9, rotation: 0 },
  },
  {
    id: 'rewardCoins',
    labelKey: 'stickerRewardCoins',
    category: 'props',
    default: { x: 0, y: 130, scale: 0.8, rotation: 0 },
  },
  {
    id: 'dramaQueen',
    labelKey: 'stickerDramaQueen',
    category: 'props',
    default: { x: -110, y: -130, scale: 0.9, rotation: 0 },
  },
  {
    id: 'couchNap',
    labelKey: 'stickerCouchNap',
    category: 'props',
    default: { x: 0, y: -130, scale: 0.9, rotation: 0 },
  },
  {
    id: 'partyHat',
    labelKey: 'stickerPartyHat',
    category: 'headwear',
    default: { x: 0, y: -125, scale: 1, rotation: 0 },
  },
  {
    id: 'santaHat',
    labelKey: 'stickerSantaHat',
    category: 'headwear',
    default: { x: 0, y: -105, scale: 1, rotation: 0 },
  },
  {
    id: 'reindeerAntlers',
    labelKey: 'stickerReindeerAntlers',
    category: 'headwear',
    default: { x: 0, y: -115, scale: 1, rotation: 0 },
  },
  {
    id: 'witchHat',
    labelKey: 'stickerWitchHat',
    category: 'headwear',
    default: { x: 0, y: -125, scale: 1, rotation: 0 },
  },
  {
    id: 'wizardHat',
    labelKey: 'stickerWizardHat',
    category: 'headwear',
    default: { x: 0, y: -125, scale: 1, rotation: 0 },
  },
  {
    id: 'birthdayHat',
    labelKey: 'stickerBirthdayHat',
    category: 'headwear',
    default: { x: 0, y: -120, scale: 0.9, rotation: 0 },
  },
  {
    id: 'sombrero',
    labelKey: 'stickerSombrero',
    category: 'headwear',
    default: { x: 0, y: -120, scale: 1.3, rotation: 0 },
  },
  {
    id: 'oktoberfestHat',
    labelKey: 'stickerOktoberfestHat',
    category: 'headwear',
    default: { x: 0, y: -110, scale: 1, rotation: 0 },
  },
  {
    id: 'smiling',
    labelKey: 'stickerSmiling',
    category: 'emojis',
    default: { x: -100, y: 100, scale: 0.8, rotation: 0 },
  },
  {
    id: 'laughingTears',
    labelKey: 'stickerLaughingTears',
    category: 'emojis',
    default: { x: 100, y: 100, scale: 0.8, rotation: 0 },
  },
  {
    id: 'heartEyes',
    labelKey: 'stickerHeartEyes',
    category: 'emojis',
    default: { x: -110, y: -20, scale: 0.8, rotation: 0 },
  },
  {
    id: 'tongueOut',
    labelKey: 'stickerTongueOut',
    category: 'emojis',
    default: { x: 110, y: -20, scale: 0.8, rotation: 0 },
  },
  {
    id: 'blowingKiss',
    labelKey: 'stickerBlowingKiss',
    category: 'emojis',
    default: { x: 0, y: -160, scale: 0.8, rotation: 0 },
  },
  {
    id: 'rollingEyes',
    labelKey: 'stickerRollingEyes',
    category: 'emojis',
    default: { x: -90, y: -140, scale: 0.7, rotation: 0 },
  },
  {
    id: 'bulgingEyes',
    labelKey: 'stickerBulgingEyes',
    category: 'emojis',
    default: { x: 90, y: -140, scale: 0.7, rotation: 0 },
  },
  {
    id: 'sunglassesEmoji',
    labelKey: 'stickerSunglassesEmoji',
    category: 'emojis',
    default: { x: 0, y: -60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'smirking',
    labelKey: 'stickerSmirking',
    category: 'emojis',
    default: { x: -110, y: 40, scale: 0.7, rotation: 0 },
  },
  {
    id: 'tongueSweat',
    labelKey: 'stickerTongueSweat',
    category: 'emojis',
    default: { x: 110, y: 40, scale: 0.7, rotation: 0 },
  },
  {
    id: 'sleepy',
    labelKey: 'stickerSleepy',
    category: 'emojis',
    default: { x: 0, y: 130, scale: 0.7, rotation: 0 },
  },
  {
    id: 'unamused',
    labelKey: 'stickerUnamused',
    category: 'emojis',
    default: { x: -60, y: -100, scale: 0.7, rotation: 0 },
  },
  {
    id: 'blushingFlustered',
    labelKey: 'stickerBlushingFlustered',
    category: 'emojis',
    default: { x: 60, y: -100, scale: 0.7, rotation: 0 },
  },
  {
    id: 'screamingInFear',
    labelKey: 'stickerScreamingInFear',
    category: 'emojis',
    default: { x: -130, y: 0, scale: 0.7, rotation: 0 },
  },
  {
    id: 'crying',
    labelKey: 'stickerCrying',
    category: 'emojis',
    default: { x: 130, y: 0, scale: 0.7, rotation: 0 },
  },
  {
    id: 'laughingDead',
    labelKey: 'stickerLaughingDead',
    category: 'emojis',
    default: { x: 0, y: 60, scale: 0.7, rotation: 0 },
  },
  {
    id: 'angrySwearing',
    labelKey: 'stickerAngrySwearing',
    category: 'emojis',
    default: { x: -60, y: 160, scale: 0.7, rotation: 0 },
  },
  {
    id: 'mindBlown',
    labelKey: 'stickerMindBlown',
    category: 'emojis',
    default: { x: 60, y: 160, scale: 0.7, rotation: 0 },
  },
  {
    id: 'heart',
    labelKey: 'stickerHeart',
    category: 'emojis',
    default: { x: -90, y: 10, scale: 0.8, rotation: 0 },
  },
  {
    id: 'poopEmoji',
    labelKey: 'stickerPoopEmoji',
    category: 'emojis',
    default: { x: 90, y: -20, scale: 0.7, rotation: 0 },
  },
  {
    id: 'coffeeMug',
    labelKey: 'stickerCoffeeMug',
    category: 'props',
    default: { x: -100, y: -20, scale: 0.7, rotation: 0 },
  },
  {
    id: 'matchaCup',
    labelKey: 'stickerMatchaCup',
    category: 'props',
    default: { x: 100, y: -20, scale: 0.7, rotation: 0 },
  },
  {
    id: 'sunglassesBlack',
    labelKey: 'stickerSunglassesBlack',
    category: 'headwear',
    default: { x: 0, y: -60, scale: 1, rotation: 0 },
  },
  {
    id: 'sunglassesAviator',
    labelKey: 'stickerSunglassesAviator',
    category: 'headwear',
    default: { x: 0, y: -60, scale: 1, rotation: 0 },
  },
  {
    id: 'speechBubble',
    labelKey: 'stickerSpeechBubble',
    category: 'emojis',
    default: { x: 110, y: -70, scale: 0.9, rotation: 0 },
  },
  {
    id: 'zzzSleep',
    labelKey: 'stickerZzzSleep',
    category: 'emojis',
    default: { x: -110, y: -70, scale: 0.8, rotation: 0 },
  },
  {
    id: 'magicWand',
    labelKey: 'stickerMagicWand',
    category: 'props',
    default: { x: 0, y: 150, scale: 0.8, rotation: 0 },
  },
  {
    id: 'cashMoney',
    labelKey: 'stickerCashMoney',
    category: 'props',
    default: { x: -120, y: 60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'peePuddle',
    labelKey: 'stickerPeePuddle',
    category: 'props',
    default: { x: 120, y: 130, scale: 0.7, rotation: 0 },
  },
  {
    id: 'dogBowl',
    labelKey: 'stickerDogBowl',
    category: 'props',
    default: { x: 0, y: 60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'beerMug',
    labelKey: 'stickerBeerMug',
    category: 'props',
    default: { x: -130, y: -40, scale: 0.7, rotation: 0 },
  },
  {
    id: 'sodaCan',
    labelKey: 'stickerSodaCan',
    category: 'props',
    default: { x: 130, y: -40, scale: 0.7, rotation: 0 },
  },
  {
    id: 'cocktail',
    labelKey: 'stickerCocktail',
    category: 'props',
    default: { x: -60, y: 120, scale: 0.7, rotation: 0 },
  },
  {
    id: 'wineGlass',
    labelKey: 'stickerWineGlass',
    category: 'props',
    default: { x: 60, y: 120, scale: 0.7, rotation: 0 },
  },
  {
    id: 'beachUmbrella',
    labelKey: 'stickerBeachUmbrella',
    category: 'props',
    default: { x: -100, y: -130, scale: 0.8, rotation: 0 },
  },
  {
    id: 'sunSticker',
    labelKey: 'stickerSunSticker',
    category: 'props',
    default: { x: 100, y: -130, scale: 0.7, rotation: 0 },
  },
  {
    id: 'palmTreeIsland',
    labelKey: 'stickerPalmTreeIsland',
    category: 'props',
    default: { x: 0, y: -20, scale: 0.8, rotation: 0 },
  },
  {
    id: 'vacationSign',
    labelKey: 'stickerVacationSign',
    category: 'props',
    default: { x: -110, y: 0, scale: 0.7, rotation: 0 },
  },
  {
    id: 'holidaySign',
    labelKey: 'stickerHolidaySign',
    category: 'props',
    default: { x: 110, y: 0, scale: 0.7, rotation: 0 },
  },
  {
    id: 'keepOutSign',
    labelKey: 'stickerKeepOutSign',
    category: 'props',
    default: { x: 0, y: 100, scale: 0.7, rotation: 0 },
  },
]
