export const STICKER_CATEGORIES = [
  { id: 'headwear', labelKey: 'stickerCategoryHeadwear' },
  { id: 'emojis', labelKey: 'stickerCategoryEmojis' },
  { id: 'police', labelKey: 'stickerCategoryPolice' },
  { id: 'props', labelKey: 'stickerCategoryProps' },
]

export const MUGSHOT_STICKERS = [
  {
    id: 'sunglasses',
    labelKey: 'stickerSunglasses',
    category: 'headwear',
    default: { x: 0, y: -60, scale: 1, rotation: 0 },
  },
  {
    id: 'cap',
    labelKey: 'stickerCap',
    category: 'headwear',
    default: { x: 0, y: -115, scale: 1, rotation: 0 },
  },
  {
    id: 'sombrero',
    labelKey: 'stickerSombrero',
    category: 'headwear',
    default: { x: 0, y: -120, scale: 1.3, rotation: 0 },
  },
  {
    id: 'banditMask',
    labelKey: 'stickerBanditMask',
    category: 'headwear',
    default: { x: 0, y: -55, scale: 1, rotation: 0 },
  },
  {
    id: 'speechBubble',
    labelKey: 'stickerSpeechBubble',
    category: 'emojis',
    default: { x: 110, y: -70, scale: 0.9, rotation: 0 },
  },
  {
    id: 'heart',
    labelKey: 'stickerHeart',
    category: 'emojis',
    default: { x: -90, y: 10, scale: 0.8, rotation: 0 },
  },
  {
    id: 'laughingEmoji',
    labelKey: 'stickerLaughingEmoji',
    category: 'emojis',
    default: { x: 90, y: 20, scale: 0.8, rotation: 0 },
  },
  {
    id: 'guiltyStampRect',
    labelKey: 'stickerGuiltyStampRect',
    category: 'police',
    default: { x: -100, y: -140, scale: 0.9, rotation: 0 },
  },
  {
    id: 'guiltyStampRound',
    labelKey: 'stickerGuiltyStampRound',
    category: 'police',
    default: { x: 100, y: 120, scale: 0.8, rotation: 0 },
  },
  {
    id: 'wantedRect',
    labelKey: 'stickerWantedRect',
    category: 'police',
    default: { x: 0, y: 140, scale: 0.9, rotation: 0 },
  },
  {
    id: 'handcuffs',
    labelKey: 'stickerHandcuffs',
    category: 'police',
    default: { x: 100, y: 60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'siren',
    labelKey: 'stickerSiren',
    category: 'police',
    default: { x: 0, y: -160, scale: 0.8, rotation: 0 },
  },
  {
    id: 'evidenceBag',
    labelKey: 'stickerEvidenceBag',
    category: 'police',
    default: { x: -110, y: 40, scale: 0.8, rotation: 0 },
  },
  {
    id: 'policeLineTape',
    labelKey: 'stickerPoliceLineTape',
    category: 'police',
    default: { x: 0, y: 0, scale: 0.9, rotation: 0 },
  },
  {
    id: 'caseClosedBoard',
    labelKey: 'stickerCaseClosedBoard',
    category: 'police',
    default: { x: 100, y: -30, scale: 0.8, rotation: 0 },
  },
  {
    id: 'innocentNote',
    labelKey: 'stickerInnocentNote',
    category: 'police',
    default: { x: -100, y: -30, scale: 0.8, rotation: 0 },
  },
  {
    id: 'goodBoyBadge',
    labelKey: 'stickerGoodBoyBadge',
    category: 'props',
    default: { x: -100, y: -100, scale: 0.9, rotation: 0 },
  },
  {
    id: 'pawMedal',
    labelKey: 'stickerPawMedal',
    category: 'props',
    default: { x: 100, y: -100, scale: 0.9, rotation: 0 },
  },
  {
    id: 'mamasHeart',
    labelKey: 'stickerMamasHeart',
    category: 'props',
    default: { x: 0, y: 100, scale: 0.9, rotation: 0 },
  },
  {
    id: 'pawPrints',
    labelKey: 'stickerPawPrints',
    category: 'props',
    default: { x: 0, y: 60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'pawNote',
    labelKey: 'stickerPawNote',
    category: 'props',
    default: { x: 0, y: -100, scale: 0.8, rotation: 0 },
  },
  {
    id: 'tennisBall',
    labelKey: 'stickerTennisBall',
    category: 'props',
    default: { x: -110, y: 100, scale: 0.7, rotation: 0 },
  },
  {
    id: 'bone',
    labelKey: 'stickerBone',
    category: 'props',
    default: { x: 110, y: 100, scale: 0.8, rotation: 0 },
  },
  {
    id: 'poop',
    labelKey: 'stickerPoop',
    category: 'props',
    default: { x: 0, y: -30, scale: 0.7, rotation: 0 },
  },
  {
    id: 'trashCan',
    labelKey: 'stickerTrashCan',
    category: 'props',
    default: { x: -90, y: -60, scale: 0.8, rotation: 0 },
  },
  {
    id: 'megaphone',
    labelKey: 'stickerMegaphone',
    category: 'props',
    default: { x: 90, y: -60, scale: 0.8, rotation: 0 },
  },
]
